[package]
name = "rust-to-cs-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
hir = { package = "ra_ap_hir", version = "0.0.331" }
hir_def = { package = "ra_ap_hir_def", version = "0.0.331" }
hir_ty = { package = "ra_ap_hir_ty", version = "0.0.331" }
syntax = { package = "ra_ap_syntax", version = "0.0.331" }
cfg = { package = "ra_ap_cfg", version = "0.0.331" }
ide_db = { package = "ra_ap_ide_db", version = "0.0.331" }
load-cargo = { package = "ra_ap_load-cargo", version = "0.0.331" }
vfs = { package = "ra_ap_vfs", version = "0.0.331" }
project_model = { package = "ra_ap_project_model", version = "0.0.331" }
rustc_type_ir = { package = "ra-ap-rustc_type_ir", version = "0.160.0" }
rustc_next_trait_solver = { package = "ra-ap-rustc_next_trait_solver", version = "0.160.0" }
tracing-subscriber = "0.3.23"
itertools = "0.14.0"
tracing = "0.1.44"
