/// Run-pass e2e tests: transpile programs from tests/run_pass/, generate a C# [Fact]
/// per program that calls m_main(), then execute them all via `dotnet test`.
///
/// A test passes when m_main() returns without throwing a PanicException.
/// This matches how rustc's run-pass tests work: the program's own assert!()
/// calls fail with a panic, which becomes PanicException in C#.
///
/// Run with: `cargo test --test run_pass_tests`

use std::path::{Path, PathBuf};
use std::process::Command;

fn transpiler_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_rust-to-cs-compiler"))
}

fn sysroot_lib() -> String {
    let out = Command::new("rustc")
        .args(["--print", "sysroot"])
        .output()
        .expect("`rustc --print sysroot` failed");
    let sysroot = std::str::from_utf8(&out.stdout)
        .expect("sysroot is not valid UTF-8")
        .trim()
        .to_owned();
    format!("{sysroot}/lib")
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Transpile a run-pass program into the Generated/ directory.
fn transpile_run_pass(input: &Path, generated_dir: &Path) -> Result<(), String> {
    let status = Command::new(transpiler_bin())
        .env("R2CS_OUTPUT_DIR", generated_dir)
        .env("LD_LIBRARY_PATH", sysroot_lib())
        .args([
            input.to_str().unwrap(),
            "--edition", "2021",
            "--crate-type", "lib",
            "-A", "dead_code",
        ])
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn transpiler: {e}"));

    if status.success() {
        Ok(())
    } else {
        Err(format!("transpiler failed on {}", input.display()))
    }
}

/// Write a C# [Fact] test class that calls `mod_<stem>.m_main()`.
fn write_cs_runner(stem: &str, runner_dir: &Path) {
    let class_name = format!("RunPass_{stem}");
    let mod_name = format!("mod_{stem}");
    let cs = format!(
        "// <auto-generated/> run-pass test for {stem}.rs\n\
         public class {class_name}\n\
         {{\n\
         \x20\x20\x20\x20[Fact]\n\
         \x20\x20\x20\x20public unsafe void test()\n\
         \x20\x20\x20\x20{{\n\
         \x20\x20\x20\x20\x20\x20\x20\x20global::{mod_name}.m_main();\n\
         \x20\x20\x20\x20}}\n\
         }}\n"
    );
    let path = runner_dir.join(format!("RunPass_{stem}.cs"));
    std::fs::write(&path, cs)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}

#[test]
fn run_pass_e2e() {
    let root = repo_root();
    let programs_dir = root.join("tests/run_pass");
    let generated_dir = root.join("dotnet/r2CsRunPassTests/Generated");
    let runner_dir = root.join("dotnet/r2CsRunPassTests/Runners");

    std::fs::create_dir_all(&generated_dir).expect("create r2CsRunPassTests/Generated/");
    std::fs::create_dir_all(&runner_dir).expect("create r2CsRunPassTests/Runners/");

    // Discover all .rs programs in tests/run_pass/.
    let mut programs: Vec<PathBuf> = std::fs::read_dir(&programs_dir)
        .expect("failed to read run_pass dir")
        .filter_map(|e| {
            let path = e.ok()?.path();
            if path.extension().and_then(|s| s.to_str()) == Some("rs") {
                Some(path)
            } else {
                None
            }
        })
        .collect();
    programs.sort();

    // Transpile and generate C# runner for each program.
    let mut failures: Vec<String> = Vec::new();
    let mut stems: Vec<String> = Vec::new();

    for prog in &programs {
        let stem = prog.file_stem().unwrap().to_string_lossy().into_owned();
        match transpile_run_pass(prog, &generated_dir) {
            Ok(()) => {
                write_cs_runner(&stem, &runner_dir);
                stems.push(stem);
            }
            Err(e) => failures.push(e),
        }
    }

    // Remove stale generated C# files from GeneratedRunPass/ (from previous runs).
    if let Ok(entries) = std::fs::read_dir(&generated_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("cs") {
                let file_stem = path.file_stem().unwrap_or_default().to_string_lossy().into_owned();
                if !stems.contains(&file_stem) {
                    let _ = std::fs::remove_file(&path);
                }
            }
        }
    }

    // Remove stale RunPass_*.cs files from previous runs.
    if let Ok(entries) = std::fs::read_dir(&runner_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("cs") {
                let name = path.file_stem().unwrap_or_default().to_string_lossy();
                // Strip "RunPass_" prefix to get the stem.
                if let Some(stem) = name.strip_prefix("RunPass_") {
                    if !stems.contains(&stem.to_string()) {
                        let _ = std::fs::remove_file(&path);
                    }
                }
            }
        }
    }

    if !failures.is_empty() {
        panic!("transpiler failures:\n{}", failures.join("\n"));
    }

    // Run dotnet test on the dedicated run-pass project.
    let project = root.join("dotnet/r2CsRunPassTests");
    let status = Command::new("dotnet")
        .args(["test", project.to_str().unwrap()])
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn `dotnet test`: {e}"));

    assert!(status.success(), "`dotnet test` failed — see output above");
}
