<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!--<ProjectReference Include="../r2CsRuntime/r2CsRuntime.csproj" />-->
    <Compile Include="../r2CsRuntime/*.cs" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Out.bak.cs" />
  </ItemGroup>

</Project>
