/// Top-level item (function, struct) code generation.
///
/// Each `compile_*` function receives a fully-analysed `TyCtxt` and emits
/// C# source text through a [`CsWriter`].

use rustc_hir::ItemKind;
use rustc_middle::ty::TyCtxt;

use crate::codegen::expr::{compile_block, ExprCtx};
use crate::codegen::naming;
use crate::codegen::types::ty_to_cs;
use crate::codegen::writer::CsWriter;

/// Compile a single free function item.
pub fn compile_fn(
    tcx: TyCtxt<'_>,
    def_id: rustc_hir::def_id::LocalDefId,
    fn_name: &str,
    w: &mut CsWriter,
) {
    let cs_name = naming::method_name(fn_name);

    // Obtain THIR for this function.
    let Ok((thir_cell, root_expr)) = tcx.thir_body(def_id) else {
        w.write_line(&format!("// THIR unavailable for {fn_name}"));
        return;
    };
    let thir = thir_cell.borrow();

    // Build the parameter list.
    let mut params: Vec<String> = Vec::new();
    for param in thir.params.iter() {
        let ty_str = ty_to_cs(tcx, param.ty)
            .unwrap_or_else(|| "object /* unknown */".into());

        let param_name = match &param.pat {
            Some(pat) => {
                use rustc_middle::thir::PatKind;
                match &pat.kind {
                    PatKind::Binding { name, .. } => {
                        naming::local_name(name.as_str(), 0)
                    }
                    _ => "_".into(),
                }
            }
            None => "_".into(),
        };
        params.push(format!("{ty_str} {param_name}"));
    }

    // Return type from the function signature via fn_sig.
    let fn_sig = tcx.fn_sig(def_id).skip_binder().skip_binder();
    let ret_ty = fn_sig.output();
    let ret_str = ty_to_cs(tcx, ret_ty)
        .unwrap_or_else(|| "object /* unknown */".into());

    // Emit function header.
    w.write_line(&format!(
        "public static {ret_str} {cs_name}({})",
        params.join(", ")
    ));
    w.write_line("{");
    w.indent();

    // Emit body via THIR block.
    let root = &thir.exprs[root_expr];
    let body_block_id = match &root.kind {
        rustc_middle::thir::ExprKind::Block { block } => *block,
        _ => {
            // Single-expression body — wrap in a synthetic return.
            let mut ctx = ExprCtx::new(tcx, &thir);
            match crate::codegen::expr::compile_expr(&mut ctx, root_expr) {
                Some(cs) => {
                    w.write_line(&format!("return {cs};"));
                }
                None => {
                    w.write_line("/* TODO: function body */");
                }
            }
            w.dedent();
            w.write_line("}");
            return;
        }
    };

    let mut ctx = ExprCtx::new(tcx, &thir);
    compile_block(&mut ctx, body_block_id, w);

    w.dedent();
    w.write_line("}");
}

/// Compile a struct definition.
pub fn compile_struct(
    tcx: TyCtxt<'_>,
    def_id: rustc_hir::def_id::LocalDefId,
    struct_name: &str,
    w: &mut CsWriter,
) {
    let cs_name = naming::struct_name(struct_name);
    let adt_def = tcx.adt_def(def_id);
    let variant = adt_def.non_enum_variant();

    w.write_line(&format!("public struct {cs_name}"));
    w.write_line("{");
    w.indent();

    for field in variant.fields.iter() {
        let field_ty = tcx.type_of(field.did).skip_binder();
        let ty_str   = ty_to_cs(tcx, field_ty)
            .unwrap_or_else(|| "object /* unknown */".into());
        let f_name   = naming::field_name(field.name.as_str());
        w.write_line(&format!("public {ty_str} {f_name};"));
    }

    w.dedent();
    w.write_line("}");
}

/// Compile all local free items in the crate, wrapped in a `mod_<crate>` class.
pub fn compile_crate(tcx: TyCtxt<'_>, w: &mut CsWriter) {
    let crate_name = tcx.crate_name(rustc_hir::def_id::LOCAL_CRATE);
    let class_name = naming::module_name(crate_name.as_str());

    w.write_line("// <auto-generated/>");
    w.write_line("#nullable enable");
    w.write_line("");
    w.write_line(&format!("public static partial class {class_name}"));
    w.write_line("{");
    w.indent();

    for item_id in tcx.hir_crate_items(()).free_items() {
        let item = tcx.hir_item(item_id);
        match item.kind {
            ItemKind::Fn { ident, .. } => {
                w.write_line("");
                compile_fn(tcx, item_id.owner_id.def_id, ident.name.as_str(), w);
            }
            ItemKind::Struct(ident, _, _) => {
                w.write_line("");
                compile_struct(tcx, item_id.owner_id.def_id, ident.name.as_str(), w);
            }
            _ => {}
        }
    }

    w.dedent();
    w.write_line("}");
}
