pub mod decl;
pub mod expr;
pub mod names;
pub mod output;
pub mod ty;

use std::collections::HashMap;

use hir::{Adt, AssocItem, Crate, DefWithBody, GenericDef, HasName, Impl, ModuleDef, db::HirDatabase};
use crate::codegen::decl::is_adt_r2cs_native;
use hir_def::{DefWithBodyId, expr_store::Body};

use self::output::Output;

pub struct CodeGenerator<'db> {
    db: &'db dyn HirDatabase,
}

impl<'db> CodeGenerator<'db> {
    pub fn new(db: &'db dyn HirDatabase) -> Self {
        Self { db }
    }

    /// Generate C# code for all declarations in a crate.
    pub fn emit_crate(&self, krate: Crate) -> String {
        let db = self.db;
        let mut out = Output::new();

        out.writeln("// Auto-generated by rust-to-cs-compiler");
        out.writeln("// Do not edit manually.");
        out.writeln("#nullable enable");
        out.writeln("using System;");
        out.writeln("using System.Collections.Generic;");
        out.writeln("using r2CsRuntime;");
        out.blank_line();

        let crate_name = krate
            .display_name(db)
            .map(|n| n.as_str().to_string())
            .unwrap_or_else(|| "r2cs_generated".to_string());
        let ns_name = names::pascal(&crate_name);
        out.writeln(&format!("namespace {};", ns_name));
        out.blank_line();

        // Collect all impls keyed by ADT (by display name as a quick proxy)
        let mut adt_impls: HashMap<String, Vec<Impl>> = HashMap::new();

        for module in krate.modules(db) {
            for impl_ in module.impl_defs(db) {
                let self_ty = impl_.self_ty(db);
                if let Some(adt) = self_ty.as_adt() {
                    let key = adt_key(adt, db);
                    adt_impls.entry(key).or_default().push(impl_);
                }
                // impls on non-ADT types (e.g. primitives, trait objects) are emitted separately
            }
        }

        // Emit traits first (no impl needed)
        for module in krate.modules(db) {
            for def in module.declarations(db) {
                if let ModuleDef::Trait(t) = def {
                    decl::emit_trait(&mut out, t, db);
                }
            }
        }

        // Emit type aliases and free functions
        for module in krate.modules(db) {
            for def in module.declarations(db) {
                if let ModuleDef::Function(f) = def {
                    // Top-level functions go in a static class per module
                    let mod_name = module.name(db)
                        .map(|n| names::mod_name(n.as_str()))
                        .unwrap_or_else(|| names::mod_name(&crate_name));
                    out.writeln(&format!("// function {} in module {}", f.name(db).as_str(), mod_name));
                    decl::emit_function(&mut out, f, db, None);
                }
            }
        }

        // Emit each ADT with its impl blocks
        for module in krate.modules(db) {
            for def in module.declarations(db) {
                match def {
                    ModuleDef::Adt(adt) => {
                        let key = adt_key(adt, db);
                        let impls = adt_impls.get(&key).cloned().unwrap_or_default();
                        self.emit_adt_with_impls(&mut out, adt, &impls);
                    }
                    _ => {}
                }
            }
        }

        out.finish()
    }

    fn emit_adt_with_impls(&self, out: &mut Output, adt: Adt, impls: &[Impl]) {
        let db = self.db;

        if is_adt_r2cs_native(adt, db) {
            let cs_name = match adt {
                Adt::Struct(s) => names::struct_name(s.name(db).as_str()),
                Adt::Enum(e) => names::struct_name(e.name(db).as_str()),
                Adt::Union(u) => names::struct_name(u.name(db).as_str()),
            };
            out.writeln(&format!("// [r2cs_native] {} — add implementation in r2CsNative/", cs_name));
            out.blank_line();
            return;
        }

        // Compute implemented interfaces
        let mut trait_interfaces: Vec<String> = Vec::new();
        for impl_ in impls {
            if let Some(trait_) = impl_.trait_(db) {
                let name = trait_.name(db);
                let cs_iface = names::trait_name(name.as_str());
                let self_cs = ty::rust_type_to_cs(&impl_.self_ty(db), db);
                // Simple form without checking generic params
                trait_interfaces.push(format!("{}<{}>", cs_iface, self_cs));
            }
        }

        let gen_params = GenericDef::from(adt).params(db);
        let (tp_names, _) = ty::generic_params_cs(&gen_params, db);
        let generics = if tp_names.is_empty() {
            String::new()
        } else {
            format!("<{}>", tp_names.join(", "))
        };

        // Build class header
        let cs_name = match adt {
            Adt::Struct(s) => names::struct_name(s.name(db).as_str()),
            Adt::Enum(e) => names::struct_name(e.name(db).as_str()),
            Adt::Union(u) => names::struct_name(u.name(db).as_str()),
        };

        let interfaces_part = if trait_interfaces.is_empty() {
            String::new()
        } else {
            format!(" : {}", trait_interfaces.join(", "))
        };

        match adt {
            Adt::Struct(s) => {
                out.writeln(&format!("public partial class {}{}{}", cs_name, generics, interfaces_part));
                out.open_brace();

                // Fields
                for field in s.fields(db) {
                    let f_ty_ns = field.ty(db);
                    let f_ty = f_ty_ns.to_type(db);
                    let cs_ty = ty::rust_type_to_cs(&f_ty, db);
                    let f_name = names::field_name(field.name(db).as_str());
                    out.writeln(&format!("public Slot<{}> {} = new(default!);", cs_ty, f_name));
                }
                if !s.fields(db).is_empty() { out.blank_line(); }

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Enum(e) => {
                out.writeln(&format!("public abstract partial class {}{}{}", cs_name, generics, interfaces_part));
                out.open_brace();
                out.writeln(&format!("private {}() {{}}", cs_name));
                out.blank_line();

                // Variants
                for variant in e.variants(db) {
                    let v_name = names::variant_name(variant.name(db).as_str());
                    let fields = variant.fields(db);
                    out.writeln(&format!("public sealed partial class {} : {}{}", v_name, cs_name, generics));
                    out.open_brace();
                    for field in &fields {
                        let f_ty_ns = field.ty(db);
                        let f_ty = f_ty_ns.to_type(db);
                        let cs_ty = ty::rust_type_to_cs(&f_ty, db);
                        let f_name = names::field_name(field.name(db).as_str());
                        out.writeln(&format!("public Slot<{}> {} = new(default!);", cs_ty, f_name));
                    }
                    out.close_brace();
                    out.blank_line();
                }

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Union(_) => {
                // Skip unions
            }
        }
    }

    fn emit_impl_methods(&self, out: &mut Output, impl_: Impl) {
        let db = self.db;
        for item in impl_.items(db) {
            if let AssocItem::Function(f) = item {
                decl::emit_function(out, f, db, Some(impl_));
            }
        }
    }
}

fn adt_key(adt: Adt, db: &dyn HirDatabase) -> String {
    let (kind, name) = match adt {
        Adt::Struct(s) => ("struct", s.name(db).as_str().to_string()),
        Adt::Enum(e) => ("enum", e.name(db).as_str().to_string()),
        Adt::Union(u) => ("union", u.name(db).as_str().to_string()),
    };
    format!("{}::{}", kind, name)
}
