#[macro_use]
pub mod output;
pub mod decl;
pub mod expr;
mod id_map;
pub mod names;
pub mod ty;

use self::output::Code;
use crate::codegen::decl::{
    is_adt_cfg_disabled, is_adt_r2cs_native, is_impl_cfg_disabled, is_module_cfg_disabled,
};
use crate::codegen::id_map::IdMap;
use crate::codegen::ty::ConstructableDef;
use hir::{
    Adt, AssocItem, Crate, GenericDef, HasSource, HirFileId, Impl, InFile, Module, ModuleDef, Name,
    Semantics, StructKind, TypeParam, db::HirDatabase,
};
use hir_def::lang_item::{LangItems, lang_items};
use hir_ty::display::DisplayTarget;
use hir_ty::next_solver::{AnyImplId, DbInterner, GenericArgs};
use ide_db::line_index;
use itertools::Itertools;
use std::collections::HashMap;
use std::env::var;
use syntax::{SyntaxNode, SyntaxNodePtr};
use vfs::{FileId, Vfs};

pub struct CodeGenerator<'db> {
    db: &'db dyn HirDatabase,
    vfs: &'db Vfs,
    krate: Crate,
    sem: Semantics<'db, dyn HirDatabase>,
    lang_items: &'db LangItems,
    interner: DbInterner<'db>,
    root_namespace: String,
    // some internal information that hard is to determine
    impl_ty_param_id: IdMap<TypeParam>,
}

impl<'db> CodeGenerator<'db> {
    pub fn new(
        db: &'db dyn HirDatabase,
        vfs: &'db Vfs,
        krate: Crate,
        root_namespace: String,
    ) -> Self {
        Self {
            db,
            vfs,
            krate,
            sem: Semantics::new_dyn(db),
            lang_items: lang_items(db, krate.base()),
            interner: DbInterner::new_with(db, krate.base()),
            root_namespace,

            impl_ty_param_id: IdMap::new("impl_"),
        }
    }

    pub fn location_with_file(
        &self,
        f: InFile<impl as_syntax_node_ptr::IntoSyntaxNodePtr>,
    ) -> String {
        let loc = self.sem.diagnostics_display_range(f.map(|x| x.as_ptr()));

        let path = self.vfs.file_path(loc.file_id);
        let line_index = line_index(self.db, loc.file_id);
        let line_col = line_index.line_col(loc.range.start());

        format!("{}:{}:{}", path, line_col.line + 1, line_col.col + 1)
    }

    pub fn display_target(&self) -> DisplayTarget {
        self.krate.to_display_target(self.db)
    }
}

pub mod as_syntax_node_ptr {
    use hir_def::expr_store::ExprOrPatPtr;
    use hir_def::nameres::ModuleSource;
    use syntax::ast::Impl;
    use syntax::{AstNode, AstPtr, SyntaxNode, SyntaxNodePtr};

    pub trait IntoSyntaxNodePtr {
        fn as_ptr(&self) -> SyntaxNodePtr;
    }

    macro_rules! impls {
        (
            $(
                |$self: tt: $ty: ty| $body: expr
            ),*
            $(,)?
        ) => {
            $(
                impl IntoSyntaxNodePtr for $ty {
                    #[inline]
                    fn as_ptr(&$self) -> SyntaxNodePtr {
                        $body
                    }
                }
            )*
        };
    }

    impls!(
        |self: SyntaxNodePtr| *self,
        |self: SyntaxNode| SyntaxNodePtr::new(self),
        |self: ModuleSource| self.node().as_ptr(),
        |self: Impl| self.syntax().as_ptr(),
    );

    impl<T: AstNode> IntoSyntaxNodePtr for AstPtr<T> {
        fn as_ptr(&self) -> SyntaxNodePtr {
            self.syntax_node_ptr()
        }
    }
}

impl<'db> CodeGenerator<'db> {
    /// Generate C# code for all declarations in a crate.
    pub fn emit_crate(&self, krate: Crate) -> String {
        let db = self.db;
        let mut out = Code::new();

        out.wln("// Auto-generated by rust-to-cs-compiler");
        out.wln("// Do not edit manually.");
        out.wln("#nullable enable");
        out.wln("using System;");
        out.wln("using System.Collections.Generic;");
        out.wln("using r2CsRuntime;");
        out.wln("using static r2CsRuntime.Helpers;");
        out.blank_line();

        let crate_name = krate
            .display_name(db)
            .map(|n| n.as_str().to_string())
            .unwrap_or_else(|| "r2cs_generated".to_string());
        out.wln(format!("namespace {};", self.root_namespace));
        out.blank_line();

        // Collect all impls keyed by ADT (by display name as a quick proxy)
        let mut adt_impls: HashMap<String, Vec<Impl>> = HashMap::new();

        for module in krate.modules(db) {
            if is_module_cfg_disabled(module, db) {
                continue;
            }
            for impl_ in module.impl_defs(db) {
                let self_ty = impl_.self_ty(db);
                if let Some(adt) = self_ty.as_adt() {
                    let key = self.adt_key(adt);
                    adt_impls.entry(key).or_default().push(impl_);
                }
            }
        }

        self.emit_module(
            &mut out,
            krate.root_module(db),
            Some(&crate_name),
            &adt_impls,
        );

        out.finish()
    }

    fn emit_module(
        &self,
        out: &mut Code,
        module: Module,
        name_override: Option<&str>,
        adt_impls: &HashMap<String, Vec<Impl>>,
    ) {
        let db = self.db;
        if is_module_cfg_disabled(module, db) {
            return;
        }

        let module_name = self.mod_simple_name(module);
        out.w(&format!("public static partial class {} ", module_name));
        out.open_brace();

        // Emit traits first (no impl needed)
        for def in module.declarations(db) {
            if let ModuleDef::Trait(t) = def {
                self.emit_trait(out, t);
            }
        }

        // Emit type aliases and free functions
        for def in module.declarations(db) {
            if let ModuleDef::Function(f) = def {
                let mod_name = self.mod_simple_name(module);
                out.wln(format!(
                    "// function {} in module {}",
                    f.name(db).as_str(),
                    mod_name
                ));
                self.emit_function(out, f, None);
            }
        }

        // Emit each ADT with its impl blocks
        for def in module.declarations(db) {
            if let ModuleDef::Adt(adt) = def {
                let key = self.adt_key(adt);
                let impls = adt_impls.get(&key).cloned().unwrap_or_default();
                self.emit_adt_with_impls(out, adt, &impls);
            }
        }

        // Emit submodules
        for def in module.declarations(db) {
            match def {
                ModuleDef::Module(module) => {
                    self.emit_module(out, module, None, adt_impls);
                }
                _ => {}
            }
        }

        out.close_brace();
    }

    fn emit_adt_with_impls(&self, out: &mut Code, adt: Adt, impls: &[Impl]) {
        let db = self.db;

        if is_adt_cfg_disabled(adt, db) {
            return;
        }

        if is_adt_r2cs_native(adt, self.krate, db) {
            let cs_name = match adt {
                Adt::Struct(s) => names::struct_name(s.name(db).as_str()),
                Adt::Enum(e) => names::struct_name(e.name(db).as_str()),
                Adt::Union(u) => names::struct_name(u.name(db).as_str()),
            };
            out.wln(format!(
                "// [r2cs_native] {} — add implementation in r2CsNative/",
                cs_name
            ));
            out.wln(format!("public partial class {cs_name} {{}}"));
            out.blank_line();
            return;
        }

        // Compute implemented interfaces
        let mut trait_interfaces: Vec<String> = Vec::new();
        for &impl_ in impls {
            if let Some(trait_) = impl_.trait_(db) {
                let cs_iface = match AnyImplId::from(impl_) {
                    AnyImplId::ImplId(impl_id) => {
                        let args = db.impl_trait(impl_id).unwrap().skip_binder().args;
                        self.trait_itf_cs1(trait_, args)
                    }
                    AnyImplId::BuiltinDeriveImplId(_) => {
                        let self_ty = impl_.self_ty(db);
                        let mut args = vec![self_ty.clone()];

                        if self.lang_items.PartialEq == Some(trait_.into()) {
                            args.push(self_ty.clone());
                        } else if self.lang_items.PartialOrd == Some(trait_.into()) {
                            args.push(self_ty.clone());
                        }

                        self.trait_itf_cs2(trait_, args)
                    }
                };
                trait_interfaces.push(cs_iface);
            }
        }

        let gen_params = GenericDef::from(adt).params(db);
        let (tp_names, constraints) = self.generic_params_cs(&gen_params);
        let generics = if tp_names.is_empty() {
            String::new()
        } else {
            format!("<{}>", tp_names.join(", "))
        };

        // Build class header
        let cs_name = names::struct_name(adt.name(db).as_str());

        let interfaces_part = if trait_interfaces.is_empty() {
            String::new()
        } else {
            format!(" : {}", trait_interfaces.join(", "))
        };

        match adt {
            Adt::Struct(s) => {
                out.wln(format!(
                    "public partial class {cs_name}{generics}{interfaces_part}",
                ));
                out.indent();
                for constraint in constraints {
                    out.w("where ").wln(constraint);
                }
                out.dedent();
                out.open_brace();

                self.emit_constructable_def(out, &cs_name, s.into());
                out.blank_line();

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Enum(e) => {
                out.wln("[global::System.Runtime.CompilerServices.UnionAttribute]");
                out.wln(format!(
                    "public sealed partial class {}{}{}",
                    cs_name, generics, interfaces_part
                ));
                out.indent();
                for constraint in constraints {
                    out.w("where ").wln(constraint);
                }
                out.dedent();
                out.open_brace();
                out.wln("private object inner;");
                out.wln("public object Value => inner;");
                out.wln(format!(
                    "public void set({cs_name}{generics} o) => inner = o.inner;"
                ));
                out.blank_line();

                // Variants
                for variant in e.variants(db) {
                    let v_name = names::variant_name(variant.name(db).as_str());
                    out.wln(format!(
                        "public {}({v_name} value) => inner = value;",
                        cs_name
                    ));
                    out.wln(format!("public sealed partial class {v_name}",));
                    out.open_brace();

                    self.emit_constructable_def(out, &v_name, variant.into());
                    out.close_brace();
                    out.blank_line();
                }

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Union(_) => {
                // Skip unions
            }
        }
    }

    fn emit_constructable_def(&self, out: &mut Code, cs_name: &str, s: ConstructableDef) {
        let db = self.db;

        // Fields
        for field in s.fields(db) {
            let f_ty_ns = field.ty(db);
            let f_ty = f_ty_ns.to_type(db);
            let cs_ty = self.rust_type_to_cs(&f_ty);
            let f_name = names::field_name(field.name(db).as_str());
            out.wln(format!("public {} {} = default!;", cs_ty, f_name));
        }

        match s.kind(self.db) {
            StructKind::Record => {}
            StructKind::Tuple => {
                if !s.fields(db).is_empty() {
                    out.blank_line();
                }
                // create tuple constructor
                out.w(code!(
                    "public static ",
                    cs_name,
                    " ctor(",
                    join(
                        s.fields(db).iter().map(|field| {
                            let f_ty_ns = field.ty(db);
                            let f_ty = f_ty_ns.to_type(db);
                            let cs_ty = self.rust_type_to_cs(&f_ty);
                            let f_name = names::field_name(field.name(db).as_str());
                            code!(cs_ty, " ", f_name)
                        }),
                        ", "
                    ),
                    ") => new ",
                    cs_name,
                    "() {\n",
                    indent,
                    join(
                        s.fields(db).iter().map(|field| {
                            let f_name = names::field_name(field.name(db).as_str());
                            code!(f_name, " = ", f_name, ",\n")
                        }),
                        ""
                    ),
                    dedent,
                    "};\n"
                ));
            }
            StructKind::Unit => {
                out.w("private ").w(cs_name).wln("(){}");
                out.w("public static ")
                    .w(cs_name)
                    .w(" instance = new ")
                    .w(cs_name)
                    .wln("();");
            }
        }
    }

    fn emit_impl_methods(&self, out: &mut Code, impl_: Impl) {
        let db = self.db;
        if is_impl_cfg_disabled(impl_, db) {
            return;
        }
        for item in impl_.items(db) {
            if let AssocItem::Function(f) = item {
                self.emit_function(out, f, Some(impl_));
            }
        }
    }

    fn adt_key(&self, adt: Adt) -> String {
        self.adt_name_cs(adt)
    }
}
