pub mod decl;
pub mod expr;
pub mod names;
pub mod output;
pub mod ty;

use std::collections::HashMap;

use self::output::Output;
use crate::codegen::decl::{
    is_adt_cfg_disabled, is_adt_r2cs_native, is_impl_cfg_disabled, is_module_cfg_disabled,
};
use crate::codegen::names::mod_name;
use hir::{
    Adt, AssocItem, Crate, GenericDef, HirFileId, Impl, Module, ModuleDef, Name, Semantics,
    db::HirDatabase,
};
use ide_db::line_index;
use syntax::SyntaxNode;
use vfs::Vfs;

pub struct CodeGenerator<'db> {
    db: &'db dyn HirDatabase,
    vfs: &'db Vfs,
    root_namespace: String,
}

impl<'db> CodeGenerator<'db> {
    pub fn new(db: &'db dyn HirDatabase, vfs: &'db Vfs, root_namespace: String) -> Self {
        Self {
            db,
            vfs,
            root_namespace,
        }
    }

    pub fn location_with_file(&self, f: HirFileId, node: SyntaxNode) -> String {
        match f {
            HirFileId::FileId(f) => {
                let file_id = f.file_id(self.db);
                let path = self.vfs.file_path(file_id);
                let line_index = line_index(self.db, file_id);
                let range = node.text_range();
                let line_col = line_index.line_col(range.start());

                return format!("{}:{}:{}", path, line_col.line, line_col.col);
            }
            HirFileId::MacroFile(m) => {
                return "macro".to_string();
            }
        }
    }
}

impl<'db> CodeGenerator<'db> {
    /// Generate C# code for all declarations in a crate.
    pub fn emit_crate(&self, krate: Crate) -> String {
        let db = self.db;
        let mut out = Output::new();

        out.writeln("// Auto-generated by rust-to-cs-compiler");
        out.writeln("// Do not edit manually.");
        out.writeln("#nullable enable");
        out.writeln("using System;");
        out.writeln("using System.Collections.Generic;");
        out.writeln("using r2CsRuntime;");
        out.blank_line();

        let crate_name = krate
            .display_name(db)
            .map(|n| n.as_str().to_string())
            .unwrap_or_else(|| "r2cs_generated".to_string());
        out.writeln(&format!("namespace {};", self.root_namespace));
        out.blank_line();

        // Collect all impls keyed by ADT (by display name as a quick proxy)
        let mut adt_impls: HashMap<String, Vec<Impl>> = HashMap::new();

        for module in krate.modules(db) {
            if is_module_cfg_disabled(module, db) {
                continue;
            }
            for impl_ in module.impl_defs(db) {
                let self_ty = impl_.self_ty(db);
                if let Some(adt) = self_ty.as_adt() {
                    let key = self.adt_key(adt, db);
                    adt_impls.entry(key).or_default().push(impl_);
                }
            }
        }

        self.emit_module(
            &mut out,
            krate.root_module(db),
            Some(&crate_name),
            &adt_impls,
        );

        out.finish()
    }

    fn emit_module(
        &self,
        out: &mut Output,
        module: Module,
        name_override: Option<&str>,
        adt_impls: &HashMap<String, Vec<Impl>>,
    ) {
        let db = self.db;
        if is_module_cfg_disabled(module, db) {
            return;
        }

        let module_name = mod_name(
            module
                .name(db)
                .as_ref()
                .map(Name::as_str)
                .or(name_override)
                .unwrap(),
        );
        out.write(&format!("public static partial class {} ", module_name));
        out.open_brace();

        // Emit traits first (no impl needed)
        for def in module.declarations(db) {
            if let ModuleDef::Trait(t) = def {
                self.emit_trait(out, t, db);
            }
        }

        // Emit type aliases and free functions
        for def in module.declarations(db) {
            if let ModuleDef::Function(f) = def {
                let mod_name = module
                    .name(db)
                    .map(|n| names::mod_name(n.as_str()))
                    .unwrap_or_else(|| {
                        names::mod_name(&module.krate(db).display_name(db).unwrap().as_str())
                    });
                out.writeln(&format!(
                    "// function {} in module {}",
                    f.name(db).as_str(),
                    mod_name
                ));
                self.emit_function(out, f, None);
            }
        }

        // Emit each ADT with its impl blocks
        for def in module.declarations(db) {
            match def {
                ModuleDef::Adt(adt) => {
                    let key = self.adt_key(adt, db);
                    let impls = adt_impls.get(&key).cloned().unwrap_or_default();
                    self.emit_adt_with_impls(out, adt, &impls);
                }
                _ => {}
            }
        }

        // Emit submodules
        for def in module.declarations(db) {
            match def {
                ModuleDef::Module(module) => {
                    self.emit_module(out, module, None, adt_impls);
                }
                _ => {}
            }
        }

        out.close_brace();
    }

    fn emit_adt_with_impls(&self, out: &mut Output, adt: Adt, impls: &[Impl]) {
        let db = self.db;

        if is_adt_cfg_disabled(adt, db) {
            return;
        }

        if is_adt_r2cs_native(adt, db) {
            let cs_name = match adt {
                Adt::Struct(s) => names::struct_name(s.name(db).as_str()),
                Adt::Enum(e) => names::struct_name(e.name(db).as_str()),
                Adt::Union(u) => names::struct_name(u.name(db).as_str()),
            };
            out.writeln(&format!(
                "// [r2cs_native] {} — add implementation in r2CsNative/",
                cs_name
            ));
            out.blank_line();
            return;
        }

        // Compute implemented interfaces
        let mut trait_interfaces: Vec<String> = Vec::new();
        for impl_ in impls {
            if let Some(trait_) = impl_.trait_(db) {
                let name = trait_.name(db);
                let cs_iface = names::trait_name(name.as_str());
                let self_cs = self.rust_type_to_cs(&impl_.self_ty(db));
                // Simple form without checking generic params
                trait_interfaces.push(format!("{}<{}>", cs_iface, self_cs));
            }
        }

        let gen_params = GenericDef::from(adt).params(db);
        let (tp_names, _) = self.generic_params_cs(&gen_params, db);
        let generics = if tp_names.is_empty() {
            String::new()
        } else {
            format!("<{}>", tp_names.join(", "))
        };

        // Build class header
        let cs_name = match adt {
            Adt::Struct(s) => names::struct_name(s.name(db).as_str()),
            Adt::Enum(e) => names::struct_name(e.name(db).as_str()),
            Adt::Union(u) => names::struct_name(u.name(db).as_str()),
        };

        let interfaces_part = if trait_interfaces.is_empty() {
            String::new()
        } else {
            format!(" : {}", trait_interfaces.join(", "))
        };

        match adt {
            Adt::Struct(s) => {
                out.writeln(&format!(
                    "public partial class {}{}{}",
                    cs_name, generics, interfaces_part
                ));
                out.open_brace();

                // Fields
                for field in s.fields(db) {
                    let f_ty_ns = field.ty(db);
                    let f_ty = f_ty_ns.to_type(db);
                    let cs_ty = self.rust_type_to_cs(&f_ty);
                    let f_name = names::field_name(field.name(db).as_str());
                    out.writeln(&format!(
                        "public Slot<{}> {} = new(default!);",
                        cs_ty, f_name
                    ));
                }
                if !s.fields(db).is_empty() {
                    out.blank_line();
                }

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Enum(e) => {
                out.writeln(&format!(
                    "public abstract partial class {}{}{}",
                    cs_name, generics, interfaces_part
                ));
                out.open_brace();
                out.writeln(&format!("private {}() {{}}", cs_name));
                out.blank_line();

                // Variants
                for variant in e.variants(db) {
                    let v_name = names::variant_name(variant.name(db).as_str());
                    let fields = variant.fields(db);
                    out.writeln(&format!(
                        "public sealed partial class {} : {}{}",
                        v_name, cs_name, generics
                    ));
                    out.open_brace();
                    for field in &fields {
                        let f_ty_ns = field.ty(db);
                        let f_ty = f_ty_ns.to_type(db);
                        let cs_ty = self.rust_type_to_cs(&f_ty);
                        let f_name = names::field_name(field.name(db).as_str());
                        out.writeln(&format!(
                            "public Slot<{}> {} = new(default!);",
                            cs_ty, f_name
                        ));
                    }
                    out.close_brace();
                    out.blank_line();
                }

                // Methods from all impl blocks
                for impl_ in impls {
                    self.emit_impl_methods(out, *impl_);
                }

                out.close_brace();
                out.blank_line();
            }
            Adt::Union(_) => {
                // Skip unions
            }
        }
    }

    fn emit_impl_methods(&self, out: &mut Output, impl_: Impl) {
        let db = self.db;
        if is_impl_cfg_disabled(impl_, db) {
            return;
        }
        for item in impl_.items(db) {
            if let AssocItem::Function(f) = item {
                self.emit_function(out, f, Some(impl_));
            }
        }
    }

    fn adt_key(&self, adt: Adt, db: &dyn HirDatabase) -> String {
        let (kind, name) = match adt {
            Adt::Struct(s) => ("struct", s.name(db).as_str().to_string()),
            Adt::Enum(e) => ("enum", e.name(db).as_str().to_string()),
            Adt::Union(u) => ("union", u.name(db).as_str().to_string()),
        };
        format!("{}::{}", kind, name)
    }
}
